# Generated by Django 3.1 on 2020-08-21 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='address2',
            new_name='default_address2',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='country',
            new_name='default_country',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='default_phone_number',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='postcode',
            new_name='default_postcode',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='street_address',
            new_name='default_street_address',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='town_or_city',
            new_name='default_town_or_city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='full_name',
        ),
    ]
