# Generated by Django 3.1 on 2020-08-22 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200821_0327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='default_email',
            field=models.EmailField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='default_full_name',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
