# Generated by Django 3.0.8 on 2020-07-18 00:15

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutaddress',
            name='user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='full_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='order_number',
            field=models.CharField(default=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='phone_number',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AddField(
            model_name='checkoutaddress',
            name='town_or_city',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=True, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='order_number',
            field=models.CharField(default=True, editable=False, max_length=32),
        ),
        migrations.AddField(
            model_name='order',
            name='phone_number',
            field=models.CharField(default=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='address_2',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='country',
            field=django_countries.fields.CountryField(default=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='postcode',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='checkoutaddress',
            name='street_address',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
