# Generated by Django 3.0.8 on 2020-07-26 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200726_0013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address2',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
