# Generated by Django 3.0.8 on 2020-07-21 03:46

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0002_auto_20200718_0015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutaddress',
            old_name='address_2',
            new_name='address2',
        ),
        migrations.AddField(
            model_name='order',
            name='address2',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(default=True, max_length=2),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='street_address',
            field=models.CharField(default=True, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='town_or_city',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
