# Generated by Django 3.1 on 2020-08-21 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_orderitem_product_size'),
        ('checkout', '0002_order_user'),
    ]

    operations = [
    ]
